# Generated by Django 2.2.1 on 2019-05-21 12:46

import ckeditor_uploader.fields
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'база знаний',
                'verbose_name_plural': 'база знаний',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Сегодня', 'Сегодня'), ('Неделя', 'Неделя'), ('Месяц', 'Месяц'), ('Год (на оборудование)', 'Год (на оборудование)')], max_length=50, verbose_name='Приоритет')),
                ('text', models.TextField(verbose_name='сообщение')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Зарегистрирована', 'Зарегистрирована'), ('Исполняется', 'Исполняется'), ('Отменена', 'Отменена'), ('Исполнена', 'Исполнена')], default='Зарегистрирована', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(max_length=50, unique=True, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('cabinet', models.CharField(max_length=5, verbose_name='Кабинет')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
