# Generated by Django 2.2.1 on 2019-05-21 17:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'база знаний',
                'verbose_name_plural': 'база знаний',
            },
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
