# Generated by Django 2.2.1 on 2019-05-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20190521_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='published',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cabinet',
            field=models.CharField(default=1, max_length=50, verbose_name='Кабинет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completion_date',
            field=models.DateTimeField(null=True, verbose_name='Срок исполнения заявки'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='published_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('День', 'День'), ('Неделя', 'Неделя'), ('Месяц', 'Месяц'), ('Год (на оборудование)', 'Год (на оборудование)')], max_length=50, verbose_name='Приоритет'),
        ),
    ]
