# Generated by Django 2.2.1 on 2019-05-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_auto_20190523_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completion_date',
            field=models.DateTimeField(null=True, verbose_name='Срок исполнения заявки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='published_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
