# Generated by Django 2.2.1 on 2019-05-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_auto_20190523_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Manual',
        ),
        migrations.AlterModelOptions(
            name='manual',
            options={'verbose_name': 'Руководство пользователя', 'verbose_name_plural': 'Руководства пользователя'},
        ),
    ]
